// SPDX-License-Identifier: BSD-3-Clause-Clear
pragma solidity ^0.8.26;

import { FHE, euint64, externalEuint64, ebool } from "@fhevm/solidity/lib/FHE.sol";
import { ZamaEthereumConfig } from "@fhevm/solidity/config/ZamaConfig.sol";

/**
 * @title PrivaDEXMatcher
 * @dev On-chain encrypted order matching using fhEVM v0.9
 *      Performs encrypted price/quantity comparison via FHE operations.
 *      Both bid and ask orders remain encrypted throughout matching.
 */
contract PrivaDEXMatcher is ZamaEthereumConfig {
    address public owner;

    struct EncryptedOrder {
        euint64 price;
        euint64 quantity;
        address trader;
        bool isBid;
        bool exists;
    }

    mapping(bytes32 => EncryptedOrder) private orders;
    mapping(bytes32 => euint64) private matchResults; // 1 if matched, 0 if not
    mapping(bytes32 => address) private matchOwners;   // bid trader for each match

    event OrderSubmitted(bytes32 indexed orderId, address indexed trader, bool isBid);
    event MatchAttempted(bytes32 indexed bidId, bytes32 indexed askId, bytes32 indexed requestId);
    event MatchResultStored(bytes32 indexed requestId, euint64 result);

    modifier onlyOwner() {
        require(msg.sender == owner, "Only owner");
        _;
    }

    constructor() {
        owner = msg.sender;
    }

    /**
     * @notice Submit an encrypted order (bid or ask) to the matcher.
     * @param orderId Unique order identifier
     * @param encryptedPrice External encrypted price (must be < 2^64)
     * @param encryptedQty External encrypted quantity (must be < 2^64)
     * @param priceProof ZK proof for price validity (generated by relayer SDK)
     * @param qtyProof ZK proof for quantity validity (generated by relayer SDK)
     * @param isBid True if this is a bid (buy order); false if ask (sell order)
     */
    function submitOrder(
        bytes32 orderId,
        externalEuint64 encryptedPrice,
        externalEuint64 encryptedQty,
        bytes calldata priceProof,
        bytes calldata qtyProof,
        bool isBid
    ) external {
        require(!orders[orderId].exists, "Order already exists");
        require(orderId != bytes32(0), "Order ID required");

        // Convert external encrypted values to euint64
        euint64 price = FHE.fromExternal(encryptedPrice, priceProof);
        euint64 qty   = FHE.fromExternal(encryptedQty,   qtyProof);

        // Grant this contract and the trader access to encrypted values
        FHE.allowThis(price);
        FHE.allowThis(qty);
        FHE.allow(price, msg.sender);
        FHE.allow(qty,   msg.sender);

        // Store the order
        orders[orderId] = EncryptedOrder({
            price:    price,
            quantity: qty,
            trader:   msg.sender,
            isBid:    isBid,
            exists:   true
        });

        emit OrderSubmitted(orderId, msg.sender, isBid);
    }

    /**
     * @notice Execute encrypted matching between a bid and ask order.
     *         All comparisons happen on encrypted values using FHE operations.
     *         Result is stored encrypted until requestPublicDecryption() is called.
     * @param bidId ID of the bid (buy) order
     * @param askId ID of the ask (sell) order
     * @return requestId Unique identifier for this match result (keccak256(bidId, askId))
     */
    function matchOrders(bytes32 bidId, bytes32 askId) external returns (bytes32 requestId) {
        require(orders[bidId].exists, "Bid order not found");
        require(orders[askId].exists, "Ask order not found");
        require(orders[bidId].isBid, "First order must be a bid");
        require(!orders[askId].isBid, "Second order must be an ask");
        require(orders[bidId].trader != orders[askId].trader, "Self-match not allowed");

        // Retrieve encrypted values
        euint64 bidPrice = orders[bidId].price;
        euint64 bidQty   = orders[bidId].quantity;
        euint64 askPrice = orders[askId].price;
        euint64 askQty   = orders[askId].quantity;

        // On-chain FHE matching logic:
        // Bid matches if: bid_price >= ask_price AND bid_qty >= ask_qty
        
        // ebool priceMatch: true if bid_price >= ask_price
        ebool priceMatch = FHE.ge(bidPrice, askPrice);
        
        // ebool qtyMatch: true if bid_qty >= ask_qty
        ebool qtyMatch = FHE.ge(bidQty, askQty);
        
        // ebool matched: true if both price and quantity conditions are met
        ebool matched = FHE.and(priceMatch, qtyMatch);
        
        // euint64 result: 1 if matched, 0 if not
        euint64 result = FHE.select(matched, FHE.asEuint64(1), FHE.asEuint64(0));

        // Compute unique request ID for this match
        requestId = keccak256(abi.encodePacked(bidId, askId));

        // Store the encrypted match result
        matchResults[requestId] = result;
        matchOwners[requestId] = orders[bidId].trader;

        // Grant ACL access: only the two traders and this contract can decrypt later
        FHE.allowThis(result);
        FHE.allow(result, orders[bidId].trader);
        FHE.allow(result, orders[askId].trader);

        emit MatchAttempted(bidId, askId, requestId);
        emit MatchResultStored(requestId, result);
    }

    /**
     * @notice Request public decryption of a match result.
     *         After calling this, the match result becomes decryptable via the relayer.
     *         Only the bid trader, ask trader, or owner can call this.
     * @param requestId The match result ID (returned from matchOrders)
     */
    function requestPublicDecryption(bytes32 requestId) external {
        require(matchOwners[requestId] != address(0), "Request ID not found");
        require(
            msg.sender == matchOwners[requestId] || msg.sender == owner,
            "Only authorized parties can request decryption"
        );
        FHE.makePubliclyDecryptable(matchResults[requestId]);
    }

    /**
     * @notice Retrieve the encrypted match result.
     *         Only the bid trader, ask trader, or owner can view.
     * @param requestId The match result ID
     * @return The encrypted match result (1 = matched, 0 = not matched)
     */
    function getMatchResult(bytes32 requestId) external view returns (euint64) {
        require(matchOwners[requestId] != address(0), "Request ID not found");
        require(
            msg.sender == matchOwners[requestId] || msg.sender == owner,
            "Only authorized parties can view this result"
        );
        return matchResults[requestId];
    }
}
