/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DarkPoolMatcherInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "getOrder"
      | "requestDecryption"
      | "submitOrder"
      | "tryMatch"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "MatchAttempted" | "MatchSettled" | "OrderSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getOrder", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "requestDecryption",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitOrder",
    values: [BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tryMatch",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOrder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestDecryption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tryMatch", data: BytesLike): Result;
}

export namespace MatchAttemptedEvent {
  export type InputTuple = [bidId: BytesLike, askId: BytesLike];
  export type OutputTuple = [bidId: string, askId: string];
  export interface OutputObject {
    bidId: string;
    askId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchSettledEvent {
  export type InputTuple = [bidId: BytesLike, askId: BytesLike];
  export type OutputTuple = [bidId: string, askId: string];
  export interface OutputObject {
    bidId: string;
    askId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderSubmittedEvent {
  export type InputTuple = [orderId: BytesLike, trader: AddressLike];
  export type OutputTuple = [orderId: string, trader: string];
  export interface OutputObject {
    orderId: string;
    trader: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DarkPoolMatcher extends BaseContract {
  connect(runner?: ContractRunner | null): DarkPoolMatcher;
  waitForDeployment(): Promise<this>;

  interface: DarkPoolMatcherInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getOrder: TypedContractMethod<
    [orderId: BytesLike],
    [
      [string, boolean, boolean] & {
        trader: string;
        exists: boolean;
        matched: boolean;
      }
    ],
    "view"
  >;

  requestDecryption: TypedContractMethod<
    [bidId: BytesLike],
    [void],
    "nonpayable"
  >;

  submitOrder: TypedContractMethod<
    [
      orderId: BytesLike,
      encryptedPrice: BytesLike,
      encryptedQty: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  tryMatch: TypedContractMethod<
    [bidId: BytesLike, askId: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getOrder"
  ): TypedContractMethod<
    [orderId: BytesLike],
    [
      [string, boolean, boolean] & {
        trader: string;
        exists: boolean;
        matched: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "requestDecryption"
  ): TypedContractMethod<[bidId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitOrder"
  ): TypedContractMethod<
    [
      orderId: BytesLike,
      encryptedPrice: BytesLike,
      encryptedQty: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "tryMatch"
  ): TypedContractMethod<
    [bidId: BytesLike, askId: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "MatchAttempted"
  ): TypedContractEvent<
    MatchAttemptedEvent.InputTuple,
    MatchAttemptedEvent.OutputTuple,
    MatchAttemptedEvent.OutputObject
  >;
  getEvent(
    key: "MatchSettled"
  ): TypedContractEvent<
    MatchSettledEvent.InputTuple,
    MatchSettledEvent.OutputTuple,
    MatchSettledEvent.OutputObject
  >;
  getEvent(
    key: "OrderSubmitted"
  ): TypedContractEvent<
    OrderSubmittedEvent.InputTuple,
    OrderSubmittedEvent.OutputTuple,
    OrderSubmittedEvent.OutputObject
  >;

  filters: {
    "MatchAttempted(bytes32,bytes32)": TypedContractEvent<
      MatchAttemptedEvent.InputTuple,
      MatchAttemptedEvent.OutputTuple,
      MatchAttemptedEvent.OutputObject
    >;
    MatchAttempted: TypedContractEvent<
      MatchAttemptedEvent.InputTuple,
      MatchAttemptedEvent.OutputTuple,
      MatchAttemptedEvent.OutputObject
    >;

    "MatchSettled(bytes32,bytes32)": TypedContractEvent<
      MatchSettledEvent.InputTuple,
      MatchSettledEvent.OutputTuple,
      MatchSettledEvent.OutputObject
    >;
    MatchSettled: TypedContractEvent<
      MatchSettledEvent.InputTuple,
      MatchSettledEvent.OutputTuple,
      MatchSettledEvent.OutputObject
    >;

    "OrderSubmitted(bytes32,address)": TypedContractEvent<
      OrderSubmittedEvent.InputTuple,
      OrderSubmittedEvent.OutputTuple,
      OrderSubmittedEvent.OutputObject
    >;
    OrderSubmitted: TypedContractEvent<
      OrderSubmittedEvent.InputTuple,
      OrderSubmittedEvent.OutputTuple,
      OrderSubmittedEvent.OutputObject
    >;
  };
}
