/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DarkPoolSettlementInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizedSettler"
      | "confidentialProtocolId"
      | "getMatchResult"
      | "registerOrder"
      | "requestPublicDecryption"
      | "setAuthorizedSettler"
      | "settleMatch"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "MatchSettled"): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizedSettler",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMatchResult",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerOrder",
    values: [BytesLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestPublicDecryption",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorizedSettler",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settleMatch",
    values: [BytesLike, BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizedSettler",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMatchResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestPublicDecryption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizedSettler",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleMatch",
    data: BytesLike
  ): Result;
}

export namespace MatchSettledEvent {
  export type InputTuple = [requestId: BytesLike];
  export type OutputTuple = [requestId: string];
  export interface OutputObject {
    requestId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DarkPoolSettlement extends BaseContract {
  connect(runner?: ContractRunner | null): DarkPoolSettlement;
  waitForDeployment(): Promise<this>;

  interface: DarkPoolSettlementInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizedSettler: TypedContractMethod<[], [string], "view">;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getMatchResult: TypedContractMethod<[requestId: BytesLike], [string], "view">;

  registerOrder: TypedContractMethod<
    [requestId: BytesLike, traderA: AddressLike, traderB: AddressLike],
    [void],
    "nonpayable"
  >;

  requestPublicDecryption: TypedContractMethod<
    [requestId: BytesLike],
    [void],
    "nonpayable"
  >;

  setAuthorizedSettler: TypedContractMethod<
    [newAuthorizedSettler: AddressLike],
    [void],
    "nonpayable"
  >;

  settleMatch: TypedContractMethod<
    [
      requestId: BytesLike,
      encPriceA: BytesLike,
      inputProofA: BytesLike,
      encPriceB: BytesLike,
      inputProofB: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizedSettler"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMatchResult"
  ): TypedContractMethod<[requestId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "registerOrder"
  ): TypedContractMethod<
    [requestId: BytesLike, traderA: AddressLike, traderB: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestPublicDecryption"
  ): TypedContractMethod<[requestId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAuthorizedSettler"
  ): TypedContractMethod<
    [newAuthorizedSettler: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settleMatch"
  ): TypedContractMethod<
    [
      requestId: BytesLike,
      encPriceA: BytesLike,
      inputProofA: BytesLike,
      encPriceB: BytesLike,
      inputProofB: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "MatchSettled"
  ): TypedContractEvent<
    MatchSettledEvent.InputTuple,
    MatchSettledEvent.OutputTuple,
    MatchSettledEvent.OutputObject
  >;

  filters: {
    "MatchSettled(bytes32)": TypedContractEvent<
      MatchSettledEvent.InputTuple,
      MatchSettledEvent.OutputTuple,
      MatchSettledEvent.OutputObject
    >;
    MatchSettled: TypedContractEvent<
      MatchSettledEvent.InputTuple,
      MatchSettledEvent.OutputTuple,
      MatchSettledEvent.OutputObject
    >;
  };
}
