/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PrivaDEXMatcherInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "getMatchResult"
      | "matchOrders"
      | "owner"
      | "requestPublicDecryption"
      | "submitOrder"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MatchAttempted"
      | "MatchResultStored"
      | "OrderSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMatchResult",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "matchOrders",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "requestPublicDecryption",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitOrder",
    values: [BytesLike, BytesLike, BytesLike, BytesLike, BytesLike, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMatchResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "matchOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestPublicDecryption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitOrder",
    data: BytesLike
  ): Result;
}

export namespace MatchAttemptedEvent {
  export type InputTuple = [
    bidId: BytesLike,
    askId: BytesLike,
    requestId: BytesLike
  ];
  export type OutputTuple = [bidId: string, askId: string, requestId: string];
  export interface OutputObject {
    bidId: string;
    askId: string;
    requestId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchResultStoredEvent {
  export type InputTuple = [requestId: BytesLike, result: BytesLike];
  export type OutputTuple = [requestId: string, result: string];
  export interface OutputObject {
    requestId: string;
    result: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderSubmittedEvent {
  export type InputTuple = [
    orderId: BytesLike,
    trader: AddressLike,
    isBid: boolean
  ];
  export type OutputTuple = [orderId: string, trader: string, isBid: boolean];
  export interface OutputObject {
    orderId: string;
    trader: string;
    isBid: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PrivaDEXMatcher extends BaseContract {
  connect(runner?: ContractRunner | null): PrivaDEXMatcher;
  waitForDeployment(): Promise<this>;

  interface: PrivaDEXMatcherInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getMatchResult: TypedContractMethod<[requestId: BytesLike], [string], "view">;

  matchOrders: TypedContractMethod<
    [bidId: BytesLike, askId: BytesLike],
    [string],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  requestPublicDecryption: TypedContractMethod<
    [requestId: BytesLike],
    [void],
    "nonpayable"
  >;

  submitOrder: TypedContractMethod<
    [
      orderId: BytesLike,
      encryptedPrice: BytesLike,
      encryptedQty: BytesLike,
      priceProof: BytesLike,
      qtyProof: BytesLike,
      isBid: boolean
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMatchResult"
  ): TypedContractMethod<[requestId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "matchOrders"
  ): TypedContractMethod<
    [bidId: BytesLike, askId: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "requestPublicDecryption"
  ): TypedContractMethod<[requestId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitOrder"
  ): TypedContractMethod<
    [
      orderId: BytesLike,
      encryptedPrice: BytesLike,
      encryptedQty: BytesLike,
      priceProof: BytesLike,
      qtyProof: BytesLike,
      isBid: boolean
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "MatchAttempted"
  ): TypedContractEvent<
    MatchAttemptedEvent.InputTuple,
    MatchAttemptedEvent.OutputTuple,
    MatchAttemptedEvent.OutputObject
  >;
  getEvent(
    key: "MatchResultStored"
  ): TypedContractEvent<
    MatchResultStoredEvent.InputTuple,
    MatchResultStoredEvent.OutputTuple,
    MatchResultStoredEvent.OutputObject
  >;
  getEvent(
    key: "OrderSubmitted"
  ): TypedContractEvent<
    OrderSubmittedEvent.InputTuple,
    OrderSubmittedEvent.OutputTuple,
    OrderSubmittedEvent.OutputObject
  >;

  filters: {
    "MatchAttempted(bytes32,bytes32,bytes32)": TypedContractEvent<
      MatchAttemptedEvent.InputTuple,
      MatchAttemptedEvent.OutputTuple,
      MatchAttemptedEvent.OutputObject
    >;
    MatchAttempted: TypedContractEvent<
      MatchAttemptedEvent.InputTuple,
      MatchAttemptedEvent.OutputTuple,
      MatchAttemptedEvent.OutputObject
    >;

    "MatchResultStored(bytes32,bytes32)": TypedContractEvent<
      MatchResultStoredEvent.InputTuple,
      MatchResultStoredEvent.OutputTuple,
      MatchResultStoredEvent.OutputObject
    >;
    MatchResultStored: TypedContractEvent<
      MatchResultStoredEvent.InputTuple,
      MatchResultStoredEvent.OutputTuple,
      MatchResultStoredEvent.OutputObject
    >;

    "OrderSubmitted(bytes32,address,bool)": TypedContractEvent<
      OrderSubmittedEvent.InputTuple,
      OrderSubmittedEvent.OutputTuple,
      OrderSubmittedEvent.OutputObject
    >;
    OrderSubmitted: TypedContractEvent<
      OrderSubmittedEvent.InputTuple,
      OrderSubmittedEvent.OutputTuple,
      OrderSubmittedEvent.OutputObject
    >;
  };
}
