# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: darkpool.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'darkpool.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x61rkpool.proto\x12\x08\x64\x61rkpool\"\xa2\x01\n\x0cMatchRequest\x12\x11\n\tbuy_order\x18\x01 \x01(\x0c\x12\x12\n\nsell_order\x18\x02 \x01(\x0c\x12\x12\n\nrequest_id\x18\x03 \x01(\t\x12\x0f\n\x07pool_id\x18\x04 \x01(\t\x12\x13\n\x0border_nonce\x18\x05 \x01(\x04\x12\x0f\n\x07use_bfv\x18\x06 \x01(\x08\x12\x11\n\ttrader_id\x18\x07 \x01(\t\x12\r\n\x05nonce\x18\x08 \x01(\x0c\"\x82\x01\n\rMatchResponse\x12\x19\n\x11result_ciphertext\x18\x01 \x01(\x0c\x12\x19\n\x11match_certificate\x18\x02 \x01(\x0c\x12\x12\n\nrequest_id\x18\x03 \x01(\t\x12\x15\n\rerror_message\x18\x04 \x01(\t\x12\x10\n\x08is_error\x18\x05 \x01(\x08\"\x1e\n\x0bPingRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0cPongResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xc9\x01\n\x0fMatchingService\x12>\n\x0bSubmitOrder\x12\x16.darkpool.MatchRequest\x1a\x17.darkpool.MatchResponse\x12?\n\x0c\x45xecuteMatch\x12\x16.darkpool.MatchRequest\x1a\x17.darkpool.MatchResponse\x12\x35\n\x04Ping\x12\x15.darkpool.PingRequest\x1a\x16.darkpool.PongResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'darkpool_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MATCHREQUEST']._serialized_start=29
  _globals['_MATCHREQUEST']._serialized_end=191
  _globals['_MATCHRESPONSE']._serialized_start=194
  _globals['_MATCHRESPONSE']._serialized_end=324
  _globals['_PINGREQUEST']._serialized_start=326
  _globals['_PINGREQUEST']._serialized_end=356
  _globals['_PONGRESPONSE']._serialized_start=358
  _globals['_PONGRESPONSE']._serialized_end=389
  _globals['_MATCHINGSERVICE']._serialized_start=392
  _globals['_MATCHINGSERVICE']._serialized_end=593
# @@protoc_insertion_point(module_scope)
