/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface PrivaDEXDarkPoolFHEVMInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "matchOrders"
      | "setSettler"
      | "settledRequestIds"
      | "settler"
      | "submitOrder"
      | "totalOrders"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "MatchExecuted" | "OrderSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "matchOrders",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSettler",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settledRequestIds",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "settler", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "submitOrder",
    values: [BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalOrders",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "matchOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setSettler", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "settledRequestIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "settler", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalOrders",
    data: BytesLike
  ): Result;
}

export namespace MatchExecutedEvent {
  export type InputTuple = [request_id: BytesLike, match_qty: BytesLike];
  export type OutputTuple = [request_id: string, match_qty: string];
  export interface OutputObject {
    request_id: string;
    match_qty: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderSubmittedEvent {
  export type InputTuple = [order_id: BigNumberish, trader: AddressLike];
  export type OutputTuple = [order_id: bigint, trader: string];
  export interface OutputObject {
    order_id: bigint;
    trader: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PrivaDEXDarkPoolFHEVM extends BaseContract {
  connect(runner?: ContractRunner | null): PrivaDEXDarkPoolFHEVM;
  waitForDeployment(): Promise<this>;

  interface: PrivaDEXDarkPoolFHEVMInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  matchOrders: TypedContractMethod<
    [orderAId: BigNumberish, orderBId: BigNumberish, request_id: BytesLike],
    [void],
    "nonpayable"
  >;

  setSettler: TypedContractMethod<
    [newSettler: AddressLike],
    [void],
    "nonpayable"
  >;

  settledRequestIds: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  settler: TypedContractMethod<[], [string], "view">;

  submitOrder: TypedContractMethod<
    [
      bidInput: BytesLike,
      askInput: BytesLike,
      qtyInput: BytesLike,
      inputProof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  totalOrders: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "matchOrders"
  ): TypedContractMethod<
    [orderAId: BigNumberish, orderBId: BigNumberish, request_id: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSettler"
  ): TypedContractMethod<[newSettler: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settledRequestIds"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "settler"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "submitOrder"
  ): TypedContractMethod<
    [
      bidInput: BytesLike,
      askInput: BytesLike,
      qtyInput: BytesLike,
      inputProof: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalOrders"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "MatchExecuted"
  ): TypedContractEvent<
    MatchExecutedEvent.InputTuple,
    MatchExecutedEvent.OutputTuple,
    MatchExecutedEvent.OutputObject
  >;
  getEvent(
    key: "OrderSubmitted"
  ): TypedContractEvent<
    OrderSubmittedEvent.InputTuple,
    OrderSubmittedEvent.OutputTuple,
    OrderSubmittedEvent.OutputObject
  >;

  filters: {
    "MatchExecuted(bytes32,bytes32)": TypedContractEvent<
      MatchExecutedEvent.InputTuple,
      MatchExecutedEvent.OutputTuple,
      MatchExecutedEvent.OutputObject
    >;
    MatchExecuted: TypedContractEvent<
      MatchExecutedEvent.InputTuple,
      MatchExecutedEvent.OutputTuple,
      MatchExecutedEvent.OutputObject
    >;

    "OrderSubmitted(uint256,address)": TypedContractEvent<
      OrderSubmittedEvent.InputTuple,
      OrderSubmittedEvent.OutputTuple,
      OrderSubmittedEvent.OutputObject
    >;
    OrderSubmitted: TypedContractEvent<
      OrderSubmittedEvent.InputTuple,
      OrderSubmittedEvent.OutputTuple,
      OrderSubmittedEvent.OutputObject
    >;
  };
}
